title: openSUSE Foobar
title_short: Foobar
description: Foobar is foobar service of openSUSE community
email: admin@opensuse.org
copyright: © 2020 openSUSE contributors
baseurl: ''
url: https://foobar.opensuse.org
github_url: https://github.com/openSUSE/foobar-o-o
weblate_url: https://l10n.opensuse.org/projects/foobar/

navbar_links:
  -
    link: https://www.opensuse.org/
    text: absolute_link
  -
    link: /about/
    text: relative_link
  - locales

footer_links:
  -
    text: source_code
    link: https://github.com/openSUSE/foobar-o-o
  -
    text: license
    link: https://github.com/openSUSE/foobar-o-o/blob/master/LICENSE

# Only edit below if you know what you are doing!

defaults:
  -
    scope:
      path: "*.html"
    values:
      layout: "default"
  -
    scope:
      path: "*.md"
    values:
      layout: "markdown"
  -
    scope:
      path: "*.markdown"
    values:
      layout: "markdown"

# search_provider: github
# search_github_repo: openSUSE/news-o-o
search_provider: duckduckgo
search_site: foobar.opensuse.org

navbar_class: navbar-expand-md sticky-top
# enable_feed: true

theme: jekyll-theme-opensuse

markdown: kramdown

plugins:
  - jekyll-locale

localization:
  mode       : auto
  locale     : en
  locales_set:
    ar:
      name: العربية
    cs:
      name: Čeština
    de:
      name: Deutsch
    el:
      name: Ελληνικά
    en:
      name: English
    es:
      name: Español
    fi:
      name: Suomi
    fr:
      name: Français
    hu:
      name: Magyar
    is:
      name: Íslenska
    it:
      name: Italiano
    ja:
      name: 日本語
    ko:
      name: 한국어
    nl:
      name: Nederlands
    pl:
      name: Polski
    pt:
      name: Português
    ru:
      name: Русский
    sv:
      name: Svenska
    tr:
      name: Türkçe
    vi:
      name: Tiếng Việt
    zh-CN:
      name: 简体中文
    zh-TW:
      name: 繁體中文

exclude: [README.md, Gemfile, Gemfile.lock, vendor]
